var ARMORS = [
    {name: 'Leather',                armor: 1,  cost: 1},
    {name: 'Chain Mail',             armor: 2,  cost: 2},
    {name: 'Plate Mail',             armor: 3,  cost: 3},
    {name: 'Plate Barding, Horses ', armor: 3,  cost: 3},
    {name: 'Flak Jacket',            armor: 4,  cost: 2},
    {name: 'Heavy Kevlar Vest',      armor: 8,  cost: 4},
    {name: 'Infantry Battle Suit',   armor: 6,  cost: 6},
    {name: 'Hard Armor',             armor: 8,  cost: 8},
    {name: 'Powered Armor, Scout',   armor: 10, cost: 10},
    {name: 'Powered Armor, Battle',  armor: 12, cost: 12},
    {name: 'Powered Armor, Heavy',   armor: 14, cost: 14},
    {name: 'Reflective Vest',        armor: 10, cost: 5},
    {name: 'Misc Armor 1st',         armor: 1,  cost: 1},
    {name: 'Misc Armor 2nd',         armor: 1,  cost: 1},
    {name: 'Misc Armor 3rd',         armor: 1,  cost: 1},
    {name: 'Misc Armor 4th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 5th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 6th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 7th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 8th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 9th',         armor: 1,  cost: 1},
    {name: 'Misc Armor 10th',        armor: 1,  cost: 1},

];
