var ARMORS = [
    {name: 'Leather', armor: 1, parry: 0, cost: 1},
    {name: 'Chain Mail', armor:	2, parry: 0, cost: 2},
    {name: 'Plate Mail', armor:3, parry: 0,	cost: 3},
    {name: 'Plate Barding (for mounts)', armor:3, parry: 0, cost: 3},
    {name: 'Shield, Small',	armor: 0, parry: 1, cost: 3},
    {name: 'Shield Medium', armor: 2, parry: 1,	cost: 5},
    {name: 'Shield Large', armor:2,	parry: 2, cost: 8},
    {name: 'Flak Jacket', armor:4, parry: 0, cost: 2},
    {name: 'Heavy Kevlar Vest', armor:8, parry: 0, cost: 4},
    {name: 'Infantry Battle Suit', armor:6, parry: 0, cost: 6},
    {name: 'Hard Armor', armor:8, parry: 0, cost: 8},
    {name: 'Powered Armor, Scout Suit', armor:10, parry: 0,	cost: 10},
    {name: 'Powered Armor, Battle Suit', armor:12, parry: 0, cost: 12},
    {name: 'Powered Armor, Heavy Suit', armor:14, parry: 0,	cost: 14},
    {name: 'Reflective Vest (vs energy only)', armor:10, parry: 0, cost: 5},
    {name: 'Misc Armor 1st', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 2nd', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 3rd', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 4th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 5th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 6th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 7th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 8th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 9th', armor: 1, parry: 0, cost: 1},
    {name: 'Misc Armor 10th', armor: 1, parry: 0, cost: 1},

];
