var EDGES = [
    {name: 'Ace', cost:	5, desc: '+2 to Boating, Driving, Piloting; may make soak rolls for his vehicle at –2'},
    {name: 'Acrobat', cost : 3, desc: '+2 to nimbleness-based Agility rolls; +1 Parry', affectedStat: 'parry', affectValue: 1},
    {name: 'Alertness', cost : 3, desc: '+2 to Smarts rolls made to notice events (such as burrowing attacks)'},
    {name: 'Ambidextrous', cost : 6, desc: 'Ignore –2 penalty for using off-hand'},
    {name: 'Arcane Background', cost : 10, desc: 'Allows access to supernatural powers (powers purchased separately)'},
    {name: 'Arcane Resistance', cost : 3, desc: 'Armor 2 vs. magic, +2 to resist powers'},
    {name: 'Improved Arcane Resistance', cost : 6, desc: 'Armor 4 vs. magic, +4 to resist magic effects'},
    {name: 'Beast Bond', cost :	3, desc: 'Character may spend bennies for animals he controls'},
    {name: 'Beast Master', cost : 0, desc: 'You gain an animal companion, paid for separately'},
    {name: 'Berserk', cost : 3, desc: 'Check the rules!'},
    {name: 'Block', cost :	3, desc: 'Parry +1', affectedStat: 'parry', affectValue: 1},
    {name: 'Improved Block', cost :	6, desc: 'Parry +2', affectedStat: 'parry', affectValue: 2},
    {name: 'Brawny', cost :	3, desc: 'Toughness +1', affectedStat: 'toughness', affectValue: 1},
    {name: 'Champion', cost : 10, desc: '+2 damage and Toughness vs. the attacks of supernaturally evil creatures (decide before the game if its unclear)'},
    {name: 'Combat Reflexes', cost : 10, desc: '+2 to recover from being Shaken'},
    {name: 'Command', cost : 5, desc: '+1 to subordinate troops within 5” to recover from being Shaken'},
    {name: 'Common Bond', cost : 3, desc: 'May spend bennies for friendly characters'},
    {name: 'Danger Sense', cost : 3, desc: 'Smarts –2 to detect surprise attacks (such as burrowing foes)'},
    {name: 'Dead Shot', cost : 3, desc: 'Double ranged damage when dealt Joker'},
    {name: 'Dodge', cost :	5, desc: '–1 to be hit with ranged attacks'},
    {name: 'Improved Dodge', cost : 10, desc: '–2 to be hit with ranged attacks'},
    {name: 'Fervor', cost : 10, desc: '+1 melee damage to subordinate troops within 5”'},
    {name: 'First Strike', cost : 5, desc: 'May instantly attack one foe who moves adjacent'},
    {name: 'Improved First Strike', cost : 10, desc: 'May instantly attack every foe who moves adjacent'},
    {name: 'Fleet Footed', cost : 3, desc: '+2 Pace, d10 running die instead of d6', affectedStat: 'pace', affectValue: 2},
    {name: 'Florentine', cost : 3, desc: '+1 vs. foes with single weapon and no shield; ignore 1 point of gang up bonus'},
    {name: 'Frenzy', cost :	3, desc: '1 extra Fighting attack at –2'},
    {name: 'Improved Frenzy', cost : 5, desc: '1 extra Fighting attack no penalty'},
    {name: 'Giant Killer', cost : 5, desc: '+1d6 damage when attacking large creatures'},
    {name: 'Hard to Kill', cost : 10, desc: 'When the character takes a wound that would put him down, roll a d6. On a 5-6, the character has 3 wounds and is Shaken instead'},
    {name: 'Harder to Kill', cost :	20, desc: 'When the character takes a wound that would put him down, roll a d6. On a 3-6, the character has 3 wounds and is Shaken instead'},
    {name: 'Healer', cost :	5, desc: '+2 to Healing rolls'},
    {name: 'Hold the Line', cost : 10, desc: 'Subordinate troops within 5” have +1 Toughness'},
    {name: 'Holy/Unholy Warrior', cost : 10, desc: 'Requires Arcane Background (MIracles). As an action, a Holy Warrior may target a supernaturally evil creature with Smarts range, which must then make a Spirit roll. Failure means it is Shaken. On a 1, it is destroyed'},
    {name: 'Inspire', cost : 10, desc: '+1 to Spirit rolls of subordinate troops within 5”'},
    {name: 'Jack of all Trades', cost : 3, desc: 'No –2 for unskilled Smarts based attempts'},
    {name: 'Level Headed', cost : 10, desc: 'Deal this unit two action cards and take the best'},
    {name: 'Improved Level Headed', cost : 15, desc: 'Deal this unit three action cards and take the best'},
    {name: 'Luck', cost : 5, desc: 'The character has an additional dedicated benny'},
    {name: 'Great Luck', cost : 10, desc: 'The character has two additional dedicated bennies'},
    {name: 'Marksman', cost : 5, desc: '+2 to Shooting rolls if the figure does not move'},
    {name: 'Mentalist', cost : 5, desc: '+2 to any opposed Psionics roll'},
    {name: 'Mighty Blow', cost : 5, desc: 'Double melee damage when dealt Joker'},
    {name: 'Mr Fix It', cost : 3, desc: '+2 to Smarts or Weird Science rolls made to repair devices'},
    {name: 'Natural Leader', cost : 5, desc: 'Leadership. Leader may give spend dedicated bennies to troops in command'},
    {name: 'Nerves of Steel', cost : 5, desc: 'Ignore 1 point of wound penalties'},
    {name: 'Improved Nerves of Steel', cost : 10, desc: 'Ignore 2 points of wound penalties'},
    {name: 'No Mercy', cost : 5, desc: 'May spend bennies on damage rolls'},
    {name: 'Occult', cost :	10, desc: 'Through knowledge or special gear, figures with this ability can harm Ethereal and Invulnerable creatures normally'},
    {name: 'Power Surge', cost : 5, desc: '+2d6 Power Points when dealt a Joker'},
    {name: 'Quick', cost : 10, desc: 'The unit cannot have an action card lower than 5 (discard and re-deal until this is true)'},
    {name: 'Rock and Roll', cost : 5, desc: 'Ignore full-auto penalty if shooter doesn’t move'},
    {name: 'Soul Drain', cost :	5, desc: 'Check the rules!'},
    {name: 'Steady Hands', cost : 5, desc: 'Ignore unstable platform penalty'},
    {name: 'Sweep', cost : 5, desc: 'Attack all adjacent foes at –2'},
    {name: 'Improved Sweep', cost : 10, desc: 'Attack all adjacent foes at no penalty'},
    {name: 'Strong Willed', cost : 3, desc: '+2 Intimidation and Taunt, and +2 to resist the same'},
    {name: 'Tough as Nails', cost :	5, desc: 'Toughness +1', affectedStat: 'toughness', affectValue: 1},
    {name: 'Improved Tough as Nails', cost : 10, desc: 'Toughness +2', affectedStat: 'toughness', affectValue: 2},
    {name: 'Trademark Weapon', cost : 3, desc: '+1 Fighting or Shooting with particular weapon'},
    {name: 'Improved Trademark Weapon', cost : 6, desc: '+2 Fighting or Shooting with particular weapon'},
    {name: 'Two Fisted', cost :	5, desc: 'May attack with a weapon in each hand without multi-action penalty'},
    {name: 'Weapon Master', cost : 5, desc: 'Parry +1', affectedStat: 'parry', affectValue: 1},
    {name: 'Master of Arms', cost :	10, desc: 'Parry +2', affectedStat: 'parry', affectValue: 2},
    {name: 'Wizard', cost :	5, desc: 'Each raise reduces the cost of a cast spell by 1 point'},
    {name: 'Woodsman', cost : 3, desc: '+2 to Stealth (Stealth may be used in certain scenarios)'}
];
