var SPECIAL_ABILITIES = [
    {name: 'Aquatic', cost:	5, desc: 'The figure ignores water-based Difficult Terrain; in deep water it moves at its listed Aquatic Pace'},
    {name: 'Bear Hug', cost: 5, desc: 'A bear hug that hits with a raise has pinned his foe. The opponent may only attempt to escape the "hug" on his action, which requires a raise on an opposed Strength roll'},
    {name: 'Burrowing', cost: 5, desc: 'Burrowing creatures can move their Pace underground (not floors, water, or other surfaces). They may attack as they emerge, making an opposed Stealth vs Smarts test. If the creature wins, it adds +2 to its attack and damage (or +4 with a raise). If the victim was on Hold, he may try to interrupt as usual'},
    {name: 'Change Form', cost:	5, desc: 'As an action, and with a Smarts roll at –2, the figure can change form into any listed type (a wolf or bat for vampires). Changing back requires a Smarts roll and is a free action'},
    {name: 'Charm', cost: 20, desc: 'Works exactly like the puppet power'},
    {name: 'Cone Attack', cost:	10, desc: 'This works exactly like a flamethrower. 2d10 Damage, Agility to avoid'},
    {name: 'Cone Attack -2', cost: 15, desc: 'Agility -2 to avoid'},
    {name: 'Constrict', cost: 5, desc: 'These creatures bite when they succeed at a Fighting roll, and entangle when they succeed with a raise. The round they entangle and each round thereafter, they cause damage to their prey equal to Str+d6. The prey may attempt to escape on his action by getting a raise on an opposed Strength roll'},
    {name: 'Children of the Night', cost: 50, desc: 'The figure can summon some other type of creatures once per game. This is a free action but requires a Smarts roll (at any applicable penalties listed in the creature’s description). The summoned creatures appear within 12" of the caster’s position, and are dealt in and act normally on the following turn.'},
    {name: 'Construct', cost: 10, desc: '+2 to recover from being Shaken, no additional damage from called shots, ignores disease and poison, Wild Card Constructs ignore wound modifiers'},
    {name: 'Death Touch', cost:	20, desc: 'These figures drain life with but a touch. Instead of a normal attack, the attacker makes a touch attack (+2 Fighting). Every raise on the roll automatically inflicts one wound to the target. This has no effect on vehicles or Constructs.'},
    {name: 'Ethereal', cost: 30, desc: 'Ignores terrain (but cannot end inside solid terrain), can only be harmed by magical weapons and attacks (including the claws or other body parts of magical creatures)'},
    {name: 'Elemental', cost: 10, desc: 'No additional damage from called shots; Fearless; Immune to disease and poison'},
    {name: 'Fear', cost: 5, desc: 'Enemy units must pass a Spirit test to enter combat with this figure, or when it moves adjacent to them, at a penalty equal to its Fear rating. This is a group roll for the entire unit. If moving to contact the creature, the unit simply refuses to do so and may not move (but may perform other actions normally). If the creature moved into contact, the unit retreats their full movement (Pace + running die) directly away. See Retreating. The cost is 3 x the Fear penalt, so Fear –2 costs 6 points.'},
    {name: 'Fear -2', cost:	8, desc: ''},
    {name: 'Fear -4', cost:	11, desc: ''},
    {name: 'Fearless', cost: 5, desc: 'The figure never suffers from Fear tests'},
    {name: 'Flees the Field', cost:	-5, desc: ''},
    {name: 'Fleet Footed d8', cost: 3, desc: 'D8 running die', affectedStat: 'pace', affectValue: 1},
    {name: 'Fleet Footed d10', cost: 5, desc: 'D10 running die', affectedStat: 'pace', affectValue: 2},
    {name: 'Flight', cost: 20, desc: 'The figure can fly, ignoring terrain effects'},
    {name: 'Gargantuan', cost: 30, desc: 'Gargantuan (size 9+) creatures have Heavy Armor, are Huge, and add their Size to their Strength roll when crushing targets via Fighting rolls'},
    {name: 'Go For The Throat', cost: 5, desc: 'The figure hits the target’s least armored area (if there is one) with a raise on its attack roll. This applies to Fighting rolls only, not ranged attacks'},
    {name: 'Gore', cost: 5, desc: 'If a figure with this ability moves at least 6" before Fighting, it adds +4 to its damage total'},
    {name: 'Hardy', cost: 10, desc: 'If this figure is Shaken, further Shaken results do not cause wounds'},
    {name: 'Heavy Armor', cost: 20, desc: "Targets protected by Heavy Armor can only be harmed by Heavy Weapons"},
    {name: 'Huge', cost: -10, desc: 'Size 6, 7 or 8. Attackers add +4 to hit'},
    {name: 'Infravision', cost:	3, desc: 'The model halves penalties (round down) for darkness when attacking all but undead (which produce no heat to detect)'},
    {name: 'Invulnerability', cost:	30, desc: 'The creature can be Shaken by any sort of attack but can only be wounded by a particular weakness, listed in its description. The weakness must be available to at least one figure on the opposing side'},
    {name: 'Large',	cost: -5, desc: 'Size 4 and 5. Attackers add +2 to hit'},
    {name: 'Low Light Vision', cost: 3, desc: 'The model ignores penalties for Dim and Dark lighting'},
    {name: 'Mist', cost: 20, desc: 'At the beginning of its turn, the figure may become Ethereal (or revert to corporeal form)'},
    {name: 'Paralysis', cost: 3, desc: 'A target who suffers damage or a Shaken result from this figure must make a Vigor roll or lose its next action'},
    {name: 'Poison', cost: 5, desc: 'A target Shaken by this figure must make a Vigor roll or be Incapacitated'},
    {name: 'Poison -2', cost: 10, desc: 'A target Shaken by this figure must make a Vigor roll at -2 or be Incapacitated'},
    {name: 'Poison -4', cost: 15, desc: 'A target Shaken by this figure must make a Vigor roll at -4 or be Incapacitated'},
    {name: 'Pounce', cost: 5, desc: 'The figure can leap 1d6" to gain +4 to its attack and damage. Its Parry is reduced by –2 until its next action when performing the maneuver however'},
    {name: 'Push', cost: 3, desc: 'The figure uses air or force to push a single target 1d6" directly away from it. The victim may make a Strength roll against the attack, with each success and raise reducing the amount he’s moved by 1'},
    {name: 'Regeneration', cost: 20, desc: 'The figure adds +2 to recover from being Shaken, and makes a Vigor roll each round at its current penalties if wounded; each success and raise removes a wound'},
    {name: 'Rollover', cost: 5, desc: 'This ability can only be used in water. If the figure hits with a raise, it causes an extra 2d4 damage to its prey in addition to its regular Strength damage'},
    {name: 'Seep', cost: 3, desc: 'Water Elemental special ability. Ignores difficult terrain and can pass through walls, doors, or anything else that isn’t air-tight'},
    {name: 'Sensors', cost:	3, desc: 'The model ignores penalties for Dim and Dark lighting'},
    {name: 'Slam', cost: 10, desc: 'Creatures such as giant worms rise up and crush their prey beneath their massive bodies. This is an opposed roll of the creature’s Fighting versus the target’s Agility. If the attacker wins, the victim suffers 4d6 damage'},
    {name: 'Small',	cost: 10, desc: 'Size -2. Attackers subtract 2 to hit'},
    {name: 'Stun', cost: 5, desc: 'When a target is hit (even if no damage is caused), it must make a Vigor roll or be Shaken'},
    {name: 'Swarm', cost: 10, desc: 'Parry +2; Because the swarm is composed of scores, hundreds, or thousands of creatures, cutting and piercing weapons do no real damage. Area-effect weapons work normally, and a figure can stomp to inflict his damage in Strength each round'},
    {name: 'Split', cost: 5, desc: 'The swarm can split into two smaller swarms (Small Burst Templates) but cannot rejoin. The Toughness of these smaller swarms is lowered by –2'},
    {name: 'Swarm Damage', cost: 10, desc: ''},
    {name: 'Undead', cost: 20, desc: '+2 Toughness, +2 to recover from being Shaken, no additional damage from called shots, immune to disease and poison, Undead Wild Cards never suffer from wound penalties', affectedStat: 'toughness', affectValue: 2},
    {name: 'Wall Walker', cost:	3, desc: 'The figure can walk up walls at their normal Pace as if they were regular terrain'},
    {name: 'Tail Lash', cost: 10, desc: 'Large creatures with long tails can sweep all opponents in their rear facing in a 3" long by 6" wide rectangle. This is a standard Fighting attack, and damage is equal to the creature’s Strength –2'},
    {name: 'Waterspout', cost: 10, desc: 'Water spirits can project a torrent of rushing water. Creatures within the cone must make a Strength roll at –2 or be Shaken'},
    {name: 'Webbing', cost:	10, desc: 'Webbing or other entanglements the size of Small Burst Templates. This is a Shooting roll with a range of 3/6/12. Anything in the web must cut or break their way free (Toughness 7). Webbed characters can still fight, but all physical actions are at –4'},
    {name: 'Whirlwind', cost: 10, desc: 'This power allows the attacker to spin or otherwise create a whirlwind around it. All foes in base contact make an opposed Strength check or are affected, incurring a –2 penalty to all actions. They may free themselves with an opposed Strength roll. If the attacker moves or is wouned, the attack is canceled and all figures are released'},
    {name: 'Wind Blast', cost: 5, desc: 'A concentrated blast of air or force using the Cone Template and a Shooting roll. Foes may make an opposed Agility roll to avoid the blast. The damage is 2d6 points of damage'}
];